apiVersion: apps/v1
kind: Deployment
metadata:
  name: wetrted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wetrted
  template:
    metadata:
      labels:
        app: wetrted
    spec:
      containers:
      - image: okteto.dev/wetrted:latest
        name: wetrted
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/comila-html.zip "
        - name: Vless_UUID
          value: "31e22b40-5408-46b9-be1c-bbc5c2c1963a"
        - name: Vless_Path
          value: "/31e22b40-5408-46b9-be1c-bbc5c2c1963a-vless"
        - name: Vmess_UUID
          value: "31e22b40-5408-46b9-be1c-bbc5c2c1963a"
        - name: Vmess_Path
          value: "/31e22b40-5408-46b9-be1c-bbc5c2c1963a-vmess"
        - name: Share_Path
          value: "/vrnk"
